config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  get "/auth/github/callback" => 'sessions#create'

  root 'welcome#index'
  get '/welcome' => 'welcome#home'

  resources :list_items, only: [:create, :destroy, :index]
  resources :lists, only: [:show, :index]
  resources :dishes, only: [:show, :index, :create]
  resources :restaurants, only: [:show, :index, :create]

  resources :users, except: [:edit, :show, :update, :destroy] do
    resources :dishes, only: [:show, :index, :new] do
      post '/tasted' => 'list_items#tasted'
    end
  end

  get '/most_popular' => 'dishes#popular'
  get '/most_popular/restaurants' => 'restaurants#popular'

end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_items
  has_many :dishes, through: :list_items

  # Create list_item in current_user's list, dish model to increases dish popularity
  def add_item(dish_id)
    self.list_items.create(dish_id: dish_id)
    @dish = Dish.find_by(id: dish_id)
    @dish.increase_popularity
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authentication_required
  layout 'application'

  def index
    @lists = List.all
  end

  # If list belongs to current_user, redirect to nested route, otherwise display list
  def show
    if params[:id].to_i == current_user.id
      redirect_to user_dishes_path(current_user)
    else
      @list = List.find_by(id: params[:id])
    end
  end

  private

  def list_params
    params.require(:list).permit(:user_id)
  end
end

app/helpers/lists_helper.rb
module ListsHelper

  def list_user
    @list.user
  end

  def self.last_updated(list)
    list.updated_at.strftime(" %B %Y")
  end
end

app/views/lists/index.html.erb
<h1>Dish-Lists</h1>

<h3>Click on a user's name to view their full Dish-List, or click preview to view without leaving this page</h3>
<br>

<ul>
  <% @lists.each do |list| %>
    <li id="<%= list.id %>"><strong><%= link_to list.user.name, list_path(list) %></strong> | Last updated: <%= ListsHelper.last_updated(list) %> | <%= link_to "preview list", list_path(list), class: "view_list", id: "#{list.id}" %></li>
    <br>
  <% end %>
</ul>

app/views/lists/show.html.erb
<h1> <%= list_user.name %>'s Dish-List</h1>
<br>

<% @list.list_items.each.with_index(1) do |list_item, i| %>
  <div class="inline">
    <strong><%= i %>.</strong>
    <%= render partial: "dishes/dish", locals: {dish: list_item.dish}%>
    <%= render partial: "dishes/add_link", locals: {dish: list_item.dish}%>
  </div><br>
<% end %>