config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  get "/auth/github/callback" => 'sessions#create'

  root 'welcome#index'
  get '/welcome' => 'welcome#home'

  resources :list_items, only: [:create, :destroy, :index]
  resources :lists, only: [:show, :index]
  resources :dishes, only: [:show, :index, :create]
  resources :restaurants, only: [:show, :index, :create]

  resources :users, except: [:edit, :show, :update, :destroy] do
    resources :dishes, only: [:show, :index, :new] do
      post '/tasted' => 'list_items#tasted'
    end
  end

  get '/most_popular' => 'dishes#popular'
  get '/most_popular/restaurants' => 'restaurants#popular'

end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant
  has_many :list_items
  has_many :lists, through: :list_items
  validates_presence_of :name
  accepts_nested_attributes_for :restaurant, reject_if: :reject_restaurant
  validate :unique_dish, :unique_restaurant
  scope :most_popular, -> {order(popularity: :desc).limit(10)}

  def reject_restaurant(attributes)
    # Reject entry of new restaurant unless all attributes present
    attributes[:name].blank? || attributes[:cuisine].blank? || attributes[:location].blank?
  end

  def unique_dish
    # Find all dishes with the name entered
    @existing_dishes = Dish.where(name: self.name)
    if !@existing_dishes.empty?
      # Check if restaurant also matches
      if @existing_dishes.any? { |dish| dish.restaurant == self.restaurant }
         errors.add(:dish, "already exists at the restaurant you selected. Please add the existing dish to your Dish-List")
      end
    end
  end

  def unique_restaurant
    # If any restaurant details have been entered
    if self.restaurant
      # If an existing restaurant has not been selected, & a new restaurant name has been entered
      if self.restaurant_id == nil && self.restaurant.name != ""
        # Find all restaurants with that name
        @existing_restaurants = Restaurant.where(name: self.restaurant.name)
        if !@existing_restaurants.empty?
          # Check if location and cuisine also match
          if @existing_restaurants.any? do |rest|
            rest.cuisine == self.restaurant.cuisine && rest.location == self.restaurant.location
            end
            errors.add(:restaurant_id, "already exists. Please select the restaurant from the list.")
          end
        end
      end
    end
  end

  def increase_popularity
    self.popularity += 1
    self.save(validate: false)
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :authentication_required
  layout 'application'

  def index
    # If accessing from nested route (user's own list)
    if params[:user_id]
      if current_user.id == params[:user_id].to_i
        @dishes = current_user.list.dishes
      else
        redirect_to dishes_path
      end
    else
    # Accessing all dishes
      @dishes = Dish.all
    end
    respond_to do |f|
      f.html {render :index}
      f.json {render :json => @dishes, each_serializer: DishSimpleSerializer}
    end
  end

  def new
    @dish = Dish.new
    @restaurants = Restaurant.all
    @restaurant = Restaurant.new
  end

  def create
    @dish = Dish.new(dish_params)
    # Check if added to restaurant from restaurant#show
    if params[:restaurant_id]
      @dish.restaurant_id = params[:restaurant_id]
    end
    if @dish.save
      # Add to users list
      add_dish_to_list(@dish)
      # redirect_to user_dishes_path(current_user), alert: "Dish successfully created and added to your list"
      respond_to do |f|
        f.html {redirect_to user_dishes_path(current_user)}
        f.json {render :json => @dish, status: 201}
      end
    else
      flash[:alert] = @dish.errors.full_messages.first
      redirect_to new_user_dish_path(current_user)
    end
  end

  def show
    @dish = Dish.find_by(id: params[:id])
    respond_to do |format|
     format.html { render :show }
     format.json { render json: @dish, include: '*'}
   end
  end

  def popular
    @dishes = Dish.most_popular
  end

  private

  # List model creates list_item
  def add_dish_to_list(dish)
    @list = current_user.list
    @list.add_item(dish.id)
  end

  def dish_params
    params.require(:dish).permit(:name, :restaurant_id, restaurant_attributes: [:name, :cuisine, :location])
  end
end

app/helpers/dishes_helper.rb
module DishesHelper

  def included_in_list(dish)
    @list = List.find_by(id: session[:user_id])
    @list.dish_ids.include?(dish.id)
  end
end

app/views/dishes/_add_link.html.erb
<% if !included_in_list(dish) %>
  <%= button_to 'add', list_items_path(dish_id: dish) %>
<% end %>

app/views/dishes/_add_remove_link.html.erb
<% if included_in_list(dish) %>
  <%= button_to "remove", list_item_path(session[:user_id]), :form => { :id => "remove_list_item"}, :method => :delete, params: {dish_id: dish.id} %>
<% else %>
  <%= button_to 'add', list_items_path(dish_id: dish) %>
<% end %>

app/views/dishes/_dish.html.erb
<%= link_to dish.name, dish_path(dish) %> | <%= dish.restaurant.name %> | <%= dish.restaurant.location %>

app/views/dishes/_dish_link.html.erb
 <p><strong><%= link_to dish.name, dish_path(dish) %></strong> | <%= dish.restaurant.name %> | <%= dish.restaurant.location %>

app/views/dishes/_list_item.html.erb
<div class="inline" id="dish-id-<%=dish.id%>">

  <% if params[:user_id] %>
    <%= render partial: "tasted_display", locals: {dish: dish} %>
  <% end %>

  <p><%= render partial: "dish", locals: {dish: dish} %></p>

  <% if params[:user_id] && !tried_dish(dish) %>
    <%= button_to "tasted", user_dish_tasted_path(dish_id: dish), :method => :post, params: {dish_id: dish.id} %>
  <% end %>

  <% if params[:user_id] %>
    <%= render partial: "add_remove_link", locals: {dish: dish} %>
  <% else %>
    <%= render partial: "add_link", locals: {dish: dish} %>
  <% end %>
  <br><br>
</div>

app/views/dishes/_new_restaurant_dish.json.erb
<%= form_for @restaurant.dishes.build, :url => dishes_path, :html => { :id => "new_restaurant_dish" } do |f| %>
  <%= f.label :name, "Dish name:" %>
  <%= f.text_field :name %>
  <%= hidden_field_tag 'restaurant_id', params[:id] %>
  <%= f.submit :class => "form-submit" %>
<% end %>

app/views/dishes/_no_dishes.html.erb
<h3>No dishes have been added yet.<br>Why don't you <%= link_to "create one?", new_user_dish_path(current_user) %></h3>

app/views/dishes/_popularity.html.erb
Added to <%= pluralize(dish.popularity, "Dish-List") %></li>

app/views/dishes/_status_display.html.erb
<% if tried_dish(dish) %>
  &#10003;
<% else %>
  &#9679;
<% end %>

app/views/dishes/_tasted_display.html.erb
<% if tried_dish(dish) %>
  &#10003;
<% else %>
  &#9679;
<% end %>

app/views/dishes/index.html.erb
<% if params[:user_id] %>
  <h1>Your Dish-List</h1>
  <h3>Every dish on your personal must-eat list</h3>
  <p>If you've tried a dish but can't wait to eat it again, mark it as tasted and leave it on your Dish-List</p>

<% else %>
  <h1>Dishes</h1>
  <h3>Every dish users are craving</h3>
<% end %>

<% if @dishes.empty? || nil %>
  <%= render partial: "no_dishes" %>

<% else %>
  <br>
  <% @dishes.each do |dish| %>
    <%= render partial: "list_item", locals: {dish: dish} %>
  <% end %>

  <% if params[:user_id] %>
    <br><br><br>
    <%= render partial: "key" %>
  <% end %>
<% end %>

app/views/dishes/new.html.erb
<h1>Add a new Dish</h1>
<h3>Straight to your Dish-List</h3>
<br>

<%= form_for @dish do |f| %>
  <%= f.label :name, "Dish name:" %>
  <%= f.text_field :name %>

  <h4>Where can you enjoy this dish?</h4>
  <p>Select existing restaurant:</p>

<%= f.collection_select :restaurant_id, @restaurants, :id, :name, :include_blank => true %>

  <p>Or create a new restaurant:</p>
  <%= f.fields_for :restaurant, @restaurant do |restaurant_fields| %>
    <%= restaurant_fields.label :name %>
    <%= restaurant_fields.text_field :name %><br><br>
    <%= restaurant_fields.label :cuisine %>
    <%= restaurant_fields.text_field :cuisine %><br><br>
    <%= restaurant_fields.label :location %>
    <%= restaurant_fields.text_field :location %><br><br>
  <% end %>

  <%= f.submit :class => "form-submit" %>
<% end %>

app/views/dishes/popular.html.erb
<h1>10 Most Popular Dishes</h1>
<h3>The dishes added to the most lists</h3>

<% if @dishes.empty? || nil %>
  <%= render partial: "no_dishes" %>

<% else %>
  <br>

  <div class="inline">
    <ol>
    <% @dishes.each.with_index(1) do |dish, i| %>
        <li>
          <%= render partial: "list_item", locals: {dish: dish, i: i} %>
          <%= render partial: "popularity", locals: {dish: dish} %><br><br>
        </li>
    <% end %>
    </ol>
  </div>
  
<% end %>

app/views/dishes/show.html.erb
<a href="#" class="js-next" data-id="<%=@dish.id%>">next dish</a>

<div class="dish-show">

  <h1><%= @dish.name %></h1>
  <h3>at <a href="/restaurants/<%= @dish.restaurant_id %>"><%= @dish.restaurant.name %></a></h3>
  <br>

  <div class="inline">
    <p><strong>Type of cuisine: </strong><%= @dish.restaurant.cuisine %></p>
  </div><br>

  <div class="inline">
    <p><strong>Location:</strong>  <%= @dish.restaurant.location %></p><br><br>
  </div><br>

  <div id="popularity">
    <%= render partial: "popularity", locals: {dish: @dish} %></h3>
  </div><br>

</div>

<!-- <div class="inline">
  <%#= render partial: "add_remove_link", locals: {dish: @dish} %>
</div> -->