config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  get "/auth/github/callback" => 'sessions#create'

  root 'welcome#index'
  get '/welcome' => 'welcome#home'

  resources :list_items, only: [:create, :destroy, :index]
  resources :lists, only: [:show, :index]
  resources :dishes, only: [:show, :index, :create]
  resources :restaurants, only: [:show, :index, :create]

  resources :users, except: [:edit, :show, :update, :destroy] do
    resources :dishes, only: [:show, :index, :new] do
      post '/tasted' => 'list_items#tasted'
    end
  end

  get '/most_popular' => 'dishes#popular'
  get '/most_popular/restaurants' => 'restaurants#popular'

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :dishes
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authentication_required
  layout 'application'

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find_by(id: params[:id])
  end

  def popular
    @restaurants = Dish.most_popular.collect {|dish| dish.restaurant}.uniq
  end
end

app/views/restaurants/_restaurant.html.erb
<div class="inline">
  <%= link_to restaurant.name, restaurant_path(restaurant) %> | <%= pluralize(restaurant.dishes.count, "Dish-List dish") %><br><br>
  Location: <%= restaurant.location %><br><br>
  Type of cuisine: <%= restaurant.cuisine %>
</div>
<br><br>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<h3>Every Dish-List worthy restaurant</h3>

<% if @restaurants.empty? || nil %>
  <%= render partial: "dishes/no_dishes" %>

<% else %>
  <br><%= render @restaurants %>
<% end %>

app/views/restaurants/popular.html.erb
<h1>Restaurants with most popular dishes</h1>
<h3>Exactly where to find our most popular dishes</h3>

<% if @restaurants.empty? || nil %>
  <%= render partial: "dishes/no_dishes" %>

<% else %>
  <br>
  <%= render @restaurants %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h3>at <%= @restaurant.location %></h3>
<br>

<strong>Type of cuisine:</strong> <%= @restaurant.cuisine %><br><br>

<h3>Dish-List dishes:</h3>

<ul id="restaurant_show">
  <% @restaurant.dishes.each do |dish| %>
      <li>
        <strong><%= link_to dish.name, dish_path(dish) %></strong> |
        <%= render partial: "dishes/popularity", locals: {dish: dish} %>
      </li><br><br>
  <% end %>
</ul>

<div id="new_dish_form"></div>

<%#= button_to  'add new dish', new_user_dish_path(user_id: current_user.id), params: {'restaurant[id]' => params[:id]} %>
<button id="button" data-restaurant-id="<%= @restaurant.id %>" data-user="<%= current_user.id %>">Add new dish</button>