config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  get "/auth/github/callback" => 'sessions#create'

  root 'welcome#index'
  get '/welcome' => 'welcome#home'

  resources :list_items, only: [:create, :destroy, :index]
  resources :lists, only: [:show, :index]
  resources :dishes, only: [:show, :index, :create]
  resources :restaurants, only: [:show, :index, :create]

  resources :users, except: [:edit, :show, :update, :destroy] do
    resources :dishes, only: [:show, :index, :new] do
      post '/tasted' => 'list_items#tasted'
    end
  end

  get '/most_popular' => 'dishes#popular'
  get '/most_popular/restaurants' => 'restaurants#popular'

end

app/views/layouts/_errors.html.erb
<%= content_tag(:div, flash[:error], :class => "errors") if flash[:error] %>
<%= content_tag(:div, flash[:notice], :class => "errors") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :class => "errors") if flash[:alert] %>

app/views/layouts/_header.html.erb
<header class="hero">
  <h1>Dish-List</h1>
  <p>a list of all the dishes you're dying to eat</p>
</header>

app/views/layouts/_navigation_images.html.erb
<% if session[:user_id] %>

  <div class="item">
    <!-- <img src="/../assets/your-list.jpg" alt="Food on table"> -->
    <%= image_tag("your-list.jpg", alt: "Food on table") %>
    <div class="item_overlay">
      <a href="/users/<%= current_user.id%>/dishes"> your dish-list </a>
    </div>
  </div>

  <div class="item">
    <!-- <img src="/../assets/add-new.jpg" alt="Doughnut"> -->
    <%= image_tag("add-new.jpg", alt: "Doughnut") %>
    <div class="item_overlay">
      <a href="/users/<%= current_user.id%>/dishes/new">create new dish</a>
    </div>
  </div>

  <div class="item">
    <!-- <img src="/../assets/all-lists.jpg" alt="Food and wine"> -->
    <%= image_tag("all-lists.jpg", alt: "Food and wine") %>
    <div class="item_overlay">
      <a href="/lists">all dish-lists</a>
    </div>
  </div>

  <div class="item">
    <!-- <img src="/../assets/most-popular.jpg" alt="Eat me neon sign"> -->
    <%= image_tag("most-popular.jpg", alt: "Eat me neon sign") %>
    <div class="item_overlay">
      <a href="/most_popular">most popular<br>dishes</a>
    </div>
</div>

  <div class="item">
    <!-- <img src="/../assets/all-dishes.jpg" alt="Hamburgers"> -->
    <%= image_tag("all-dishes.jpg", alt: "Hamburgers") %>
    <div class="item_overlay">
      <a href="/dishes">all dishes</a>
    </div>
  </div>

  <div class="item">
    <!-- <img src="/../assets/popular-restaurants.jpg" alt="Burgers on counter"> -->
    <%= image_tag("popular-restaurants.jpg", alt: "Burgers on counter") %>
    <div class="item_overlay">
      <a href="/most_popular/restaurants">most popular<br>restaurants</a>
    </div>
  </div>

  <div class="item">
    <!-- <img src="/../assets/all-restaurants.jpg" alt="Restaurant interior"> -->
    <%= image_tag("all-restaurants.jpg", alt: "Restaurant interior") %>
    <div class="item_overlay">
      <a href="/restaurants">all restaurants</a>
    </div>
  </div>

  <% if current_page?(welcome_path) %>
    <div class="item">
      <!-- <img src="/../assets/profile.jpg" alt="Paper and pen"> -->
      <%= image_tag("profile.jpg", alt: "Paper and pen") %>
      <div class="item_overlay">
        <a href="/welcome">homepage</a>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation_links.html.erb
<nav class="menu">
  <% if session[:user_id] %>|
  
    <% unless current_page?(welcome_path) %>
      <%= link_to "Homepage", welcome_path %> |
    <% end %>

    <% unless current_page?(user_dishes_path(session[:user_id])) %>
      <%= link_to "View your Dish-List", user_dishes_path(current_user) %> |
    <% end %>

    <% unless current_page?(new_user_dish_path(session[:user_id])) %>
      <%= link_to "Create a new Dish for your List", new_user_dish_path(session[:user_id]) %> |
    <% end %>

    <% unless current_page?(lists_path) %>
      <%= link_to "View all Dish-Lists", lists_path %> |
    <% end %>

    <% unless current_page?(most_popular_path) %>
      <%= link_to "View most popular dishes", most_popular_path %> |
    <% end %>

    <% unless current_page?(dishes_path) %>
      <%= link_to "View all dishes", dishes_path %> |
    <% end %>

    <% unless current_page?(most_popular_restaurants_path) %>
      <%= link_to "View restaurants with most popular dishes", most_popular_restaurants_path %>
    <% end %> |

    <% unless current_page?(restaurants_path) %>
      <%= link_to "View all restaurants", restaurants_path %> |
    <% end %>

  <% end %>
</nav>

app/views/layouts/_placeholder_images.erb
<div class="item">
  <!-- <img src="/../assets/your-list.jpg" alt="Food on table"> -->
  <%= image_tag("your-list.jpg", alt: "Food on table") %>
</div>

<div class="item">
  <!-- <img src="/../assets/add-new.jpg" alt="Doughnut"> -->
  <%= image_tag("add-new.jpg", alt: "Doughnut") %>
</div>

<div class="item">
  <!-- <img src="/../assets/all-lists.jpg" alt="Food and wine"> -->
  <%= image_tag("all-lists.jpg", alt: "Food and wine") %>
</div>

<div class="item">
  <%= image_tag("most-popular.jpg", alt: "Eat me neon sign") %>
  <!-- <img src="/../assets/most-popular.jpg" alt="Eat me neon sign"> -->
</div>

<div class="item">
  <%= image_tag("all-dishes.jpg", alt: "Hamburgers") %>
  <!-- <img src="/../assets/all-dishes.jpg" alt="Hamburgers"> -->
</div>

<div class="item">
  <%= image_tag("popular-restaurants.jpg", alt: "Burgers on counter") %>
  <!-- <img src="/../assets/popular-restaurants.jpg" alt="Burgers on counter"> -->
</div>

<div class="item">
  <%= image_tag("all-restaurants.jpg", alt: "Restaurant interior") %>
  <!-- <img src="/../assets/all-restaurants.jpg" alt="Restaurant interior"> -->
</div>

<div class="item">
  <%= image_tag("profile.jpg", alt: "Paper and pen") %>
  <!-- <img src="/../assets/profile.jpg" alt="Paper and pen"> -->
</div>

app/views/layouts/_profile_links.html.erb
<div class="profile_links">

  <% if session[:user_id] %>
    Signed in as <%= current_user.name %> | <%= current_user.email %> |
    <%= link_to 'Sign out', logout_path, method: :post %>
  <% else %>
    | <%= link_to 'Sign in', login_path %> |
    <%= link_to 'Sign up', new_user_path %> |
    <%= link_to "Sign in with Github", '/auth/github' %> |
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DishList</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="top">
        <%= render partial: "layouts/header" %>
        <%= render partial: "layouts/navigation_links" %>
      </div>

      <div class="content">
        <%= render partial: "layouts/errors" %>
        <%= yield %>
      </div>

      <div class="sidebar">
        <% if current_user %>
          <%= render partial: "layouts/navigation_images" %>
        <% else %>
          <%= render partial: "layouts/placeholder_images" %>
        <% end %>
      </div>

      <footer><%= render partial: "layouts/profile_links" %></footer>
    </div>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DishList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'landing', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="top">
        <%= render partial: "layouts/header" %>
        <%= render partial: "layouts/profile_links" %>
      </div>

      <div class="content">
        <%= render partial: "layouts/errors" %>
        <%= yield %>

        <div class="index-images">
          <%= render partial: "layouts/placeholder_images" %>
        </div>
      </div>

    </div>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DishList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'welcome', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="top">
        <%= render partial: "layouts/header" %>
        <%= render partial: "layouts/navigation_links" %>
      </div>

      <%= yield %>

      <div class="sidebar">
        <%= render partial: "layouts/navigation_images" %>
      </div>

      <footer><%= render partial: "layouts/profile_links" %></footer>
    </div>
  </body>
</html>